Models/ClienteModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//Para especificar los datos necesarios.
using System.ComponentModel.DataAnnotations;

namespace MVC_Contactos.Models
{
    public class ClienteModel
    {
        public int IdCliente { get; set; }

        [Required]
        public string? Nombre { get; set; }

        [Required]
        public int NumDocumento { get; set; }

        [Required]
        public string? Direccion { get; set; }
        
        [Required]
        public string? Telefono { get; set; }
        [Required]
        public string? Email { get; set; }
    }
}

Models/EmpleadoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Contactos.Models
{
    public class EmpleadoModel
    {
        public int IdEmpleado { get; set; }
        [Required]
        public string? Nombre { get; set; }
        [Required]
        public int? NumDocumento { get; set; }
        [Required]
        public string? Direccion { get; set; }
        [Required]
        public string? Telefono { get; set; }
        [Required]
        public string? Email { get; set; }
        [Required]
        public string? DatosAdicionales { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace MVC_Contactos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProductoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Contactos.Models
{
    public class ProductoModel
    {
        public int IdProducto { get; set; }
        public int IdCategoria { get; set; }
        public string? Nombre { get; set; }
        public int Codigo { get; set; }
        public int PrecioCompra { get; set; }
        public int PrecioVenta { get; set; }
        public string? Detalle { get; set; }
        public string? Foto { get; set; }
        public int NumStock { get; set; }

        
    }
}

Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Contactos.Data;
using MVC_Contactos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Contactos.Controllers
{
    public class ClienteController : Controller
    {

        ClienteData cliente = new ClienteData();

        public IActionResult MostarClientes()
        {
            var oLista = cliente.Listarclientes();
            //Motrar la lista de clientes
            return View(oLista);
        }

        public IActionResult GuardarClientes()
        {
            //Solo devuelve la vista(después de realizar una posible actualización o guardado de datos)
            return View();
        }

        [HttpPost]
        //Para obtener los datos del formulario y mandarlos
        public IActionResult GuardarClientes(ClienteModel oCliente)
        {
            if (!ModelState.IsValid)
                return View();

            
            var repuesta = cliente.Guardarcliente(oCliente);
            if (repuesta)
            
                return RedirectToAction("MostarClientes");
            else
            //Recibr objeto y guardarlo en la base de datos
            return View();
        }

        public IActionResult EditarClientes(int IdCliente)
        {
            //Solo devuelve la vista(después de realizar una posible actualización o guardado de datos)
            var oCliente = cliente.Obtenercliente(IdCliente);
            return View(oCliente);
        }

        [HttpPost]
        //Para obtener los datos del formulario y mandarlos
        public IActionResult EditarClientes(ClienteModel oCliente)
        {
            if (!ModelState.IsValid)
                return View();


            var repuesta = cliente.EditarCliente(oCliente);
            if (repuesta)

                return RedirectToAction("MostarClientes");
            else
                //Recibr objeto y guardarlo en la base de datos
                return View();
        }

        public IActionResult EliminarClientes(int IdCliente)
        {
            //Solo devuelve la vista(después de realizar una posible actualización o guardado de datos)
            var oCliente = cliente.Obtenercliente(IdCliente);
            return View(oCliente);
        }

        [HttpPost]
        //Para obtener los datos del formulario y mandarlos
        public IActionResult EliminarClientes(ClienteModel oCliente)
        {
           var repuesta = cliente.EliminarCliente(oCliente.IdCliente);
            if (repuesta)

                return RedirectToAction("MostarClientes");
            else
                //Recibr objeto y guardarlo en la base de datos
                return View();
        }

    }
}

Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Contactos.Data;
using MVC_Contactos.Models;


namespace MVC_Contactos.Controllers
{
    public class EmpleadoController : Controller
    {

        EmpleadoData empleado = new EmpleadoData();

        public IActionResult MostrarEmpleado()
        {
            var oLista = empleado.ListarEmpleados();
            //Motrar la lista de clientes
            return View(oLista);
        }

        public IActionResult GuardarEmpleado()
        {
            //Solo devuelve la vista(después de realizar una posible actualización o guardado de datos)
            return View();
        }

        [HttpPost]
        //Para obtener los datos del formulario y mandarlos
        public IActionResult GuardarEmpleado(EmpleadoModel oEmpleado)
        {
            if (!ModelState.IsValid)
                return View();


            var repuesta = empleado.GuardarEmpleado(oEmpleado);
            if (repuesta)

                return RedirectToAction("MostrarEmpleado");
            else
                //Recibr objeto y guardarlo en la base de datos
                return View();
        }

        public IActionResult EditarEmpleado(int IdEmpleado)
        {
            //Solo devuelve la vista(después de realizar una posible actualización o guardado de datos)
            var oEmpleado = empleado.ObtenerEmpleado(IdEmpleado);
            return View(oEmpleado);
        }

        [HttpPost]
        //Para obtener los datos del formulario y mandarlos
        public IActionResult EditarEmpleado(EmpleadoModel oEmpleado)
        {
            if (!ModelState.IsValid)
                return View();


            var repuesta = empleado.EditarEmpleado(oEmpleado);
            if (repuesta)

                return RedirectToAction("MostrarEmpleado");
            else
                //Recibr objeto y guardarlo en la base de datos
                return View();
        }

        public IActionResult EliminarEmpleado(int IdEmpleado)
        {
            //Solo devuelve la vista(después de realizar una posible actualización o guardado de datos)
            var oEmpleado = empleado.ObtenerEmpleado(IdEmpleado);
            return View(oEmpleado);
        }

        [HttpPost]
        //Para obtener los datos del formulario y mandarlos
        public IActionResult EliminarEmpleado(EmpleadoModel oEmpleado)
        {
            var repuesta = empleado.EliminarEmpleado(oEmpleado.IdEmpleado);
            if (repuesta)

                return RedirectToAction("MostrarEmpleado");
            else
                //Recibr objeto y guardarlo en la base de datos
                return View();
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Contactos.Models;
using System.Diagnostics;

namespace MVC_Contactos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cliente/EditarClientes.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "EditarClientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Editar cliente
  </div>
  <div class="card-body">
  <form asp-action="EditarClientes" asp-controller="Cliente" method="post">
      <input asp-for="IdCliente" type="hidden" class="form-control" >
      <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input asp-for="Nombre" type="text" class="form-control" >
        <span asp-validation-for="Nombre" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label class="form-label">Documento</label>
        <input asp-for="NumDocumento" type="number" class="form-control" >
        <span asp-validation-for="NumDocumento" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label  class="form-label">Dirección</label>
        <input asp-for="Direccion" type="text" class="form-control" >
        <span asp-validation-for="Direccion" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label  class="form-label">Teléfono</label>
        <input asp-for="Telefono" type="number" class="form-control">
        <span asp-validation-for="Telefono" class="text-danger"></span>
      </div>
      <div class="mb-3">
        <label  class="form-label">Email </label>
        <input asp-for="Email" type="text" class="form-control"  >
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      
      <button type="submit" class="btn btn-primary">Guardar</button>

      <a asp-action="MostarClientes" asp-controller="Cliente" class="btn btn-success ">Regresar</a>
   </form>
  </div>
</div>

Views/Cliente/EliminarClientes.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "EliminarClientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Eliminar cliente
  </div>
  <div class="card-body">
  <form asp-action="EliminarClientes" asp-controller="Cliente" method="post">
      <input asp-for="IdCliente" type="hidden" class="form-control" >
            
      
       <div class="alert alert-danger" role="alert">
          ¿Desea eliminar el contacto: @Html.DisplayTextFor(m => m.Nombre)?
        </div>
        <button type="submit" class="btn btn-primary">Eliminar</button>
      <a asp-action="MostarClientes" asp-controller="Cliente" class="btn btn-success ">Regresar</a>
   </form>
  </div>
</div>

Views/Cliente/GuardarClientes.cshtml
<!--Establecemos el modelo a utilizar-->
@model ClienteModel
@{
    ViewData["Title"] = "GuardarClientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
  <div class="card-header">
    Crear cliente
  </div>
  <div class="card-body">
  <form asp-action="GuardarClientes" asp-controller="Cliente" method="post">
      <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input asp-for="Nombre" type="text" class="form-control" >
        <span asp-validation-for="Nombre" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label class="form-label">Documento</label>
        <input asp-for="NumDocumento" type="number" class="form-control" >
        <span asp-validation-for="NumDocumento" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label  class="form-label">Dirección</label>
        <input asp-for="Direccion" type="text" class="form-control" >
        <span asp-validation-for="Direccion" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label  class="form-label">Teléfono</label>
        <input asp-for="Telefono" type="number" class="form-control">
        <span asp-validation-for="Telefono" class="text-danger"></span>
      </div>
      <div class="mb-3">
        <label  class="form-label">Email </label>
        <input asp-for="Email" type="text" class="form-control"  >
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      
      <button type="submit" class="btn btn-primary">Guardar</button>

      <a asp-action="MostarClientes" asp-controller="Cliente" class="btn btn-success ">Regresar</a>
   </form>
  </div>
</div>

Views/Cliente/MostarClientes.cshtml
@model List<ClienteModel>
@{
    ViewData["Title"] = "MostarClientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Lista clientes
  </div>
  <div class="card-body">
    <a asp-action="GuardarClientes" asp-controller="Cliente" class="btn btn-success ">Crear nuevo cliente</a>
      <hr />
   <table class="table table-bordered">
       <thead>
           <tr>
               <th>Nombre</th>
               <th>Documento</th>
               <th>Dirección</th>
               <th>Teléfono</th>
               <th>Email</th>
               <th>Acciones</th>
           </tr> 
       </thead>
       <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.NumDocumento</td>
                        <td>@item.Direccion</td>
                        <td>@item.Telefono</td>
                        <td>@item.Email</td>
                        <td>
                            <a asp-action="EditarClientes" asp-controller="Cliente" class="btn btn-primary btn-sm" asp-route-IdCliente="@item.IdCliente">Editar</a>
                            <a asp-action="EliminarClientes" asp-controller="Cliente" class="btn btn-danger btn-sm" asp-route-IdCliente="@item.IdCliente">Eliminar</a>
                        </td>

                    </tr>
                }
       </tbody>
   </table>
  </div>
</div>

Views/Empleado/EditarEmpleado.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "EditarEmpleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Editar
  </div>
  <div class="card-body">
  <form asp-action="EditarEmpleado" asp-controller="Empleado" method="post">
      <input asp-for="IdEmpleado" type="hidden" class="form-control" >
      <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input asp-for="Nombre" type="text" class="form-control" >
        <span asp-validation-for="Nombre" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label class="form-label">Documento</label>
        <input asp-for="NumDocumento" type="number" class="form-control" >
        <span asp-validation-for="NumDocumento" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label  class="form-label">Dirección</label>
        <input asp-for="Direccion" type="text" class="form-control" >
        <span asp-validation-for="Direccion" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label  class="form-label">Teléfono</label>
        <input asp-for="Telefono" type="number" class="form-control">
        <span asp-validation-for="Telefono" class="text-danger"></span>
      </div>
      <div class="mb-3">
        <label  class="form-label">Email </label>
        <input asp-for="Email" type="text" class="form-control"  >
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label for="form-label" class="form-label">Datos adicionales</label>
        <textarea asp-for="DatosAdicionales" type="text" class="form-control" rows="3"></textarea>
        <span asp-validation-for="DatosAdicionales" class="text-danger"></span>
      </div>
      
      <button type="submit" class="btn btn-primary">Editar</button>

      <a asp-action="MostrarEmpleado" asp-controller="Empleado" class="btn btn-success ">Regresar</a>
   </form>
  </div>
</div>

Views/Empleado/EliminarEmpleado.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "EliminarEmpleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Eliminar empleado
  </div>
  <div class="card-body">
  <form asp-action="EliminarEmpleado" asp-controller="Empleado" method="post">
      <input asp-for="IdEmpleado" type="hidden" class="form-control" >
            
      
       <div class="alert alert-danger" role="alert">
          ¿Desea eliminar el contacto: @Html.DisplayTextFor(m => m.Nombre)?
        </div>
        <button type="submit" class="btn btn-primary">Eliminar</button>
      <a asp-action="MostarEmpleado" asp-controller="Empleado" class="btn btn-success ">Regresar</a>
   </form>
  </div>
</div>

Views/Empleado/GuardarEmpleado.cshtml
<!--Establecemos el modelo a utilizar-->
@model EmpleadoModel
@{
    ViewData["Title"] = "GuardarEmpleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
  <div class="card-header">
    Crear empleado
  </div>
  <div class="card-body">
  <form asp-action="GuardarEmpleado" asp-controller="Empleado" method="post">
      <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input asp-for="Nombre" type="text" class="form-control" >
        <span asp-validation-for="Nombre" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label class="form-label">Documento</label>
        <input asp-for="NumDocumento" type="number" class="form-control" >
        <span asp-validation-for="NumDocumento" class="text-danger"></span>
        
      </div>
      <div class="mb-3">
        <label  class="form-label">Dirección</label>
        <input asp-for="Direccion" type="text" class="form-control" >
        <span asp-validation-for="Direccion" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label  class="form-label">Teléfono</label>
        <input asp-for="Telefono" type="number" class="form-control">
        <span asp-validation-for="Telefono" class="text-danger"></span>
      </div>
      <div class="mb-3">
        <label  class="form-label">Email </label>
        <input asp-for="Email" type="text" class="form-control"  >
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label for="form-label" class="form-label">Datos adicionales</label>
        <textarea asp-for="DatosAdicionales" type="text" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      
      <button type="submit" class="btn btn-primary">Guardar</button>

      <a asp-action="MostrarEmpleado" asp-controller="Empleado" class="btn btn-success ">Regresar</a>
   </form>
  </div>
</div>

Views/Empleado/MostrarEmpleado.cshtml
@model List<EmpleadoModel>
@{
    ViewData["Title"] = "MostrarEmpleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Lista de empleados
  </div>
  <div class="card-body">
    <a asp-action="GuardarEmpleado" asp-controller="Empleado" class="btn btn-success ">Crear empleado</a>
      <hr />
   <table class="table table-bordered">
       <thead>
           <tr>
               <th>Nombre</th>
               <th>Documento</th>
               <th>Dirección</th>
               <th>Teléfono</th>
               <th>Email</th>
               <th>Acciones</th>
           </tr> 
       </thead>
       <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        
                        <td>@item.Nombre</td>
                        <td>@item.NumDocumento</td>
                        <td>@item.Direccion</td>
                        <td>@item.Telefono</td>
                        <td>@item.Email</td>
                        <td>
                            <a asp-action="EditarEmpleado" asp-controller="Empleado" class="btn btn-primary btn-sm" asp-route-IdEmpleado="@item.IdEmpleado">Editar</a>
                            <a asp-action="EliminarEmpleado" asp-controller="Empleado" class="btn btn-danger btn-sm" asp-route-IdEmpleado="@item.IdEmpleado">Eliminar</a>
                            </td>

                    </tr>
                }
       </tbody>
   </table>
  </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Contactos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Contactos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Contactos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="MostrarEmpleado">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="MostarClientes">Clientes</a>
                        </li>
                                                                                                                                
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_Contactos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>